spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.87.157:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://139.155.87.157:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


dubbo:
  scan:
    base-packages: com.xiayu.demo.business.controller,com.xiayu.demo.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://139.155.87.157:8848
    provider:
      loadbalance: roundrobin  #负载均衡方式  轮循
      # random 随机，roundrobin 轮循，leastactive 最少活跃调用数，consistenthash一致性 Hash

server:
  port: 9002

management:
  endpoints:
    web:
      exposure:
        include: "*"
#外部配置
business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret

# 开启 Feign 的 OKHttp 方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false